version: '3.8'

services:
  web-blue:
    build: ./app1
    container_name: app-blue
    ports:
      - "8081:80"
    restart: unless-stopped

  web-green:
    build: ./app2
    container_name: app-green
    ports:
      - "8082:80"
    restart: unless-stopped
  
  web-red:
    build: ./app3
    container_name: app-red
    ports:
      - "8083:80"
    restart: unless-stopped
    
      