name: Deploy to Proxmox # Просто имя пайплайна

#Время запуска пайплайна, то есть on значит на что реагировать, в даной ситуации на push
on:
  push: #Когда пуш
    branches: # В ветку
      - main # Название ветки
  workflow_dispatch: # разрешает запуск пайплайна из интерфейса гитеи

# Что делать
jobs:
  deploy-containers:
    runs-on: ubuntu-latest
    # Когда подняли ранер на убунте, он передал гитее "Я умею вполнять задачу с тегом ubuntu-latest"
    # Гитея когда видит файл, отправляет ранерам сообщение - "Кто работает с ubuntu-latest?"
    # Ранер забирает задачу

    steps:
    #Качаем код из репозитория
    - name: Checkout Code
      uses: actions/checkout@v4 
      #это стандартный плагин который делает git clone репозитория внутрь рабочей папки ранера на сервере

    - name: Restart Docker Compost
      run: |
        docker compose down
        docker compose up -d --build
    #1) удаляет старые контейнеры, если они были запущены
    #2) поднимает новые контейнеры в фоновом режиме