FROM nginx:alpine
#FROM - фундамент, говорим возьми уже готовую ОС Alpine с установленым Nginx
COPY . /usr/share/nginx/html/
#ADD - возьми все (точка - .) что лежит в папке app1 то есть index.html с нашим веб сайтом и копироват его в директорию nginx index.html